### PR TITLE
Update KDL SegmentMap interface to use shared pointers

### PR DESCRIPTION
**Pull request by jensenb**
This is a dependent change for the orocos KDL API modification discussed in: orocos/orocos_kinematics_dynamics#4

To summarize the KDL API used incomplete type definitions in STL containers, which is undefined behaviour according the c++ standard. As it was, GCC / libstc++ handles this behaviour with problems; however, on systems with clang/libc++ using incomplete type definitions in STL containers results in compilation errors. Instead a solution involving shared pointers has been proposed. More rational the change is discussed in the upstream pull request.

The upstream pull request is necessary for this change to be merged.

### CODE REVIEW

**Comment by wjwwood** [comment]
Just like discussed in https://github.com/ros/robot_state_publisher/pull/5 we need to figure out when and where this change will need to be deployed to line up with the new release of `orocos_kdl` unless we make this change backwards compatible.

**Comment by jensenb** [comment]
Updated this PR to reflect the newest changes in the upstream pull request.

It seems I accidentally rebased on indigo-devel, is this a big problem?

**Comment by isucan** [comment]
Not at all. All these changes should actually be rebased for indigo, and sent for the indigo-devel branches.

**Comment by jensenb** [comment]
Now that the change has been merged upstream I properly rebased on hydro-devel.

**Comment by jensenb** [comment]
I completely forgot to check up on the PR, is there anything holding this back currently from being merged into hydo-devel and indigo-devel?

**Comment by NikolausDemmel** [comment]
bump

EDIT: The bump is about getting these changes released into hydro/indigo in a coordinatd fashion: ros/robot_model#43, ros/robot_state_publisher#5, #4, #19

**Comment by NikolausDemmel** [comment]
Now that orocos_kdl has been re-released (https://github.com/smits/orocos-kdl-release) including the patch that this PR depends on, can we merge this and https://github.com/ros/robot_model/pull/60 and then possibly some time get a hydro and an indigo release?

**Comment by wjwwood** [comment]
@NikolausDemmel do these need to be `#ifdef` guarded based on the KDL behavior? Or will this new API usage always be available?

**Comment by NikolausDemmel** [comment]
No `#ifdef` needed for the open PRs AFACT. The `GetTreeElementChildren` accessor was introduced by the released patches as a compatibility layer and should work with both API variants.

@jensenb: Am I right?

**Comment by wjwwood** [comment]
Ok, I see now, I think you are right @NikolausDemmel.

**Comment by wjwwood** [comment]
@isucan with your permission I would merge and release this at least into Indigo, but probably also Hydro. Otherwise you can do it, but I know you are busy.

**Comment by jensenb** [comment]
@NikolausDemmel That is how it was intended. That is the best way i could come up with to mask the underlying API.

**Comment by isucan** [comment]
Releasing would be great! Thanks!

**Comment by wjwwood** [comment]
Sorry I just realized you wanted me to release, doing it now.

**Comment by wjwwood** [comment]
@isucan is hydro ok for release? (also your accidental version bump to 1.11.0 in hydro-devel some how resulted in no 1.10.19 tag, so I fixed that) I'm a little weary about releasing hydro given the set of changes.

**Comment by wjwwood** [comment]
These are the changes: https://github.com/ros/robot_model/compare/1.10.19...hydro-devel

**Comment by NikolausDemmel** [comment]
These are the changes that were already on `hydro-devel` even before this patch? Or were these pulled in due to merging the patch that was prepared for indigo-devel into hdyro-devel? If the latter is the case, it would maybe be better to roll back and cherry pick just this patch onto the last hydro release.

**Comment by wjwwood** [comment]
@NikolausDemmel I'm not sure, this pull request was only one commit, but it is possible something got messed up and the indigo changes ended up on the hydro branch by accident. That's why I am going to wait on @isucan to give the green light on the pending changes for hydro first.

**Comment by isucan** [comment]
@NikolausDemmel I am not sure which changes you are referring to. Are they from a different commit? If something got accidentally merged from indigo, I agree we should remove it. If it's something that does not break ABI though, it should be fine.

**Comment by NikolausDemmel** [comment]
Sorry for the confusion.

@isucan: I'm talking about the changes in https://github.com/ros/robot_model/compare/1.10.19...hydro-devel, i.e. all changes on hydro-devel since the last hydro commit. All these would be released into hydro if a release were done now. Only the last two commits and the one from March 7 are relevant to this patch. Ignore my comment about them possibly being merged inadvertedly from indigo-devel; I just looked at the commit graph again; that doesn't seem to be the case.

So the remaining question from @wjwwood to you, @isucan, is to confirm that robot_model should indeed be released into hydro, given that this would not only release the patches relevant to this KDL issue, but also all the other patches shown in https://github.com/ros/robot_model/compare/1.10.19...hydro-devel. If you give your ok, William will do the release.

**Comment by wjwwood** [comment]
@isucan Yeah, @NikolausDemmel has it right, I'm looking for a :+1:/:-1: from you.

**Comment by isucan** [comment]
You guys are awesome! Thanks for making it so easy for me. +1 @wjwwood

**Comment by wjwwood** [comment]
Ok, pulling the trigger.

**Comment by wjwwood** [comment]
https://github.com/ros/rosdistro/pull/5191

**Pull request merged**
