### PR TITLE
scroll joint_state_publisher if there are too many joints

### PR DESCRIPTION
**Pull request by v4hn**
Otherwise joints are hidden with wxgtk3

### CODE REVIEW

**Comment by v4hn** [comment]
I know this is obsolete because of the rqt implementation in kinetic.
Still, I thought the diff is worth putting it somewhere...

**Comment by jackieokay** [comment]
Works for me, thank you for the fix.

**Comment by jackieokay** [comment]
It would be cool if you could look into using the equivalent scrollbar widget in the Qt version in kinetic-devel too.

**Comment by v4hn** [comment]
If I get annoyed enough by it once I moved to kinetic,
I'll probably do that :)

Thanks for merging!

**Pull request merged**
