### PR TITLE
fix wrong inertia coordinates

### PR DESCRIPTION
**Pull request by YoheiKakiuchi**
Collada parser returns wrong inertia frame when root link has translation(and or rotation).
I attached patch to fix it.
This has already sent to https://code.ros.org/trac/ros-pkg/ticket/5609.

### CODE REVIEW

**Comment by wjwwood** [comment]
@isucan Can you review this patch?

**Comment by isucan** [comment]
@wjwwood already on it

**Comment by isucan** [comment]
@YoheiKakiuchi Thank you for your patch!
Your comment on https://code.ros.org/trac/ros-pkg/ticket/5609 says the solution is 'not so good' but works well. You also seem to be doing multiple inverse on the same matrix in the code. Can you elaborate on the problem fixed and why you think the solution is not so good?

**Comment by YoheiKakiuchi** [comment]
Intertial frame in collada file should be set as relative coordinates to RootLink.
RootLink is not world origin, but root of links. This is defined in the collada specification.
So, I added global variable _RootOrigin as coordinates of root of links.
Then, I multiply inertial frame represented on world coordinates by inverse of _RootOrigin.

This practically works well. 'doing multiple inverse on the same matrix in the code' and using global variable for temporary coordinates could be refined.

**Comment by isucan** [comment]
Thanks for the info!

**Pull request merged**
