### PR TITLE
link libpcrecpp before other libraries

### PR DESCRIPTION
**Pull request by k-okada**
fix #106 was not perfect, we need to link pcrecpp before othre libraries

### CODE REVIEW

**Comment by k-okada** [comment]
we need either #108 or #107, I'm afraid that #108 may not effective if something has changed, #107 seems more robust for this type of issue. but at this moment changing robot_model is very riskey so we should choose #107 for indigo and #108 for jade or k-turtle, 

I used this launch file for testing.

```
<launch>
  <!-- sudo apt-get install ros-hydro-openhrp3 -->
  <arg name="COLLADA_FILE" value="/opt/ros/indigo/share/OpenHRP-3.1/sample/model/PA10/pa10.main.dae" />
  <param name="robot_description" textfile="$(arg COLLADA_FILE)" />
  <node pkg="robot_state_publisher" type="state_publisher" name="hrpsys_state_publisher" />
</launch>
```

**Comment by k-okada** [comment]
@isucan I think we can merge this PR (and release this before next indigo release is out) , which is just changes the order of link libraries.

**Comment by isucan** [comment]
Merged, but this is very fragile indeed

**Comment by k-okada** [comment]
thanks!

**Pull request merged**
