### PR TITLE
fix missed mandatory -std=c++11 flag

### PR DESCRIPTION
**Pull request by 4eetah**
collada_parser,kdl_parser,urdf: add c++11 flag,
collada_parser: replace typeof with ansi __typeof__
builded/tested on gentoo

### CODE REVIEW

**Comment by 4eetah** [comment]
Can't actually reproduce the build failure on gentoo, build and tests compiled smoothly

**Comment by wjwwood** [comment]
Well, we'll have a look at it asap, but if you have time to look at the error and reason about it then that would be good. I can't merge the patch if it doesn't build on our main target platform (Ubuntu Xenial for Kinetic).

**Comment by 4eetah** [comment]
I actually looked at it, that's why I mentioned I can't reproduce the issue on my machine. Seems like the modules build is ok, the tests build fails though, can't really think of how this patch might affect the tests.

**Comment by wjwwood** [comment]
`add_compile_options` applies to the whole folder, so it would also affect the tests. It is likely that something about the combination of the explicit `-std=c++11` combined with the version of gcc on Xenial has broken something in the tests. As I said, we'll get to it asap, but it probably won't be for a while.

**Comment by 4eetah** [comment]
:+1: there are two of them std::isnan and boost::math::isnan
so after including c++11 isnan seems like an issue
for some reason they don't interfere on my machine =)

**Comment by wjwwood** [comment]
Thanks! @clalancette or @sloretz can one of you review this after the build farm comes back with a result and then merge if it looks good to you?

**Comment by wjwwood** [comment]
Unfortunately we now have a compiler warning which is new with C++11 :stuck_out_tongue_closed_eyes:. I think the right thing to do is to disable this warning when importing from collada (source of the issue) using pragma's, see:

https://gcc.gnu.org/onlinedocs/gcc/Diagnostic-Pragmas.html

Perhaps @clalancette or @sloretz could help with that, unless @den4ix feels comfortable doing it.

**Comment by 4eetah** [comment]
this becoming kinda funny, I hope it won't produce another warn/err =)

**Comment by wjwwood** [comment]
Awesome, build farm is happy now, thanks!

**Review by sloretz — APPROVED** [review]
Looks good to me

**Comment by sloretz** [comment]
@wjwwood I noticed a similar pull request #145 tries to be windows compatible. Is that a standard pull requests should be held to going forwards?

**Comment by wjwwood** [comment]
Windows support is "nice to have", but I don't ask others to do in pr's because we have no CI that tests it on Windows for them, and I don't expect them to be able to do so. One of us could extend this pr to support Windows if we had the interest and time to do so, but I don't right now.

**Pull request merged**
