### PR TITLE
kdl_parser: Adding python kdl parser

### PR DESCRIPTION
**Pull request by jbohren**
Example:

``` python
import kdl_parser
(ok, tree) = kdl_parser.urdf.treeFromFile('/path/to/file.urdf')
```

### CODE REVIEW

**Comment by isucan** [comment]
This looks great Jonathan, can we have this as a separate kdl_parser_py package?

**Comment by peter-lehner** [comment]
I would like to use the python kdl parser. If I can help create the package please let me know.

**Comment by jbohren** [comment]
@peter-lehner Feel free to derive a new PR from this one, I think @isucan just wants it in it's own package called `kdl_parser_py`.

**Comment by jackieokay** [comment]
hey @jbohren:

I shuffled the Python parser into a new package in this branch:

https://github.com/ros/robot_model/tree/kdl_parser_py

I'm now working on porting the `kdl_parser` test to Python so that it works with the new parser.

**Comment by jackieokay** [comment]
Alright, the branch mentioned in the above comment should have everything working now. I wrote a small test (https://github.com/ros/robot_model/blob/kdl_parser_py/kdl_parser_py/test/test_kdl_parser.py) that passes on my machine.

**Comment by jackieokay** [comment]
I started another PR for this with the branch I started. I'll probably merge that one and close this, if that's ok.

**Comment by jackieokay** [comment]
Closing this since the other PR has been merged. thanks again @jbohren

**Pull request closed without merging**
