### PR TITLE
Add missing namespaces

### PR DESCRIPTION
**Pull request by jspricke**

### CODE REVIEW

**Comment by wjwwood** [comment]
Can you provide some context as to why this is needed? Should the `*SharedPtr` typedefs be inside a namespace (`urdf`) as well? @rhaschke

**Comment by jspricke** [comment]
`ModelInterface` is in the `urdf` namespace, so we have to add it, otherwise gcc complains. Adding the namespace to the `*SharedPtr` definitely makes sense. Actually why not move them into `urdf/include/urdf/model.h`?

**Comment by rhaschke** [comment]
I don't see a reason, why the explicit namespace is needed. All these types are declared within a `namespace urdf`. Some older gcc might have issues with that.
Moving the declaration to `urdf/include/urdf/model.h` doesn't make sense, as `ModelInterface`is a type defined by `urdfdom_headers`, not the `urdf`package. However, I suggested to have this declaration in `urdf_headers`instead: https://github.com/ros/urdfdom_headers/pull/33. Unfortunately, nobody commented on this idea yet.

**Review by rhaschke — CHANGES_REQUESTED** [review]
To be on the safe side, I suggest to explicitly state `::urdf::ModelInterface`.

**Comment by jspricke** [comment]
`urdf` namespace ends in line 72 whereas these defines are in 78ff. gcc 6.2.0 (current Debian unstable) complained.

**Comment by rhaschke** [comment]
> urdf namespace ends in line 72 whereas these defines are in 78ff. gcc 6.2.0 (current Debian unstable) complained.

Oh, indeed. I missed that. In this case, please extend the namespace to lines 78ff. as the SharedPtr types should reside in that namespace too as suggested in https://github.com/ros/robot_model/pull/165#issuecomment-258577466.

**Comment by jspricke** [comment]
Tested and works fine with new added namespace

**Comment by jspricke** [comment]
I've inegrated this into #144.

**Pull request closed without merging**
