### PR TITLE
Strip collada indigo

### PR DESCRIPTION
**Pull request by sloretz**
Part of #195 for indigo-devel

This removes the collada packages and adds a readme with their new locations.

### CODE REVIEW

**Comment by sloretz** [comment]
Merged now that collada_urdf and collada_parser have been released to indigo and jade from the new repository

**Comment by k-okada** [comment]
Can we revert this please? Because we have been using robot_model with collada functionality in indigo and in general we'd better to apply significant change toward upcoming ros-distros, that's why you have distro based branches in this package.

**Comment by sloretz** [comment]
Hi @k-okada! `collada_parser` and `collada_urdf` are still part of the `robot_model` metapackage in Indigo. All that has changed is the source code lives on the branch `indigo-devel` at https://github.com/ros/collada_urdf

**Comment by 130s** [comment]
I can only assume that the reason this change is needed is for the ease of maintenance, particularly backporting the changes from newer distros is much easier if the older distro sits in the same repo.

Looking at the commit history at [indigo-devel](https://github.com/ros/robot_model/commits/indigo-devel), I'd say there has been only manageable number of activities for the last one year. So if I had been in the shoe of the maintainer I would have only applied this change to the upcoming distro (`Lunar`), and kept branches for the already-released distros in the old repo (`robot_model`) IMHO (and many packages depend on these fundamental packages in ROS needless to say).

**Comment by sloretz** [comment]
Thanks for the feedback @130s. Like you mentioned, I think the collada_parser source code should be kept together to ease maintenance on both the maintainers and the users. If the code is in two places it becomes difficult for users to know where to open issues and pull requests.

I think the reasons to keep the source code together are stronger than the reasons to split the source code by ROS distribution. The API and ABI is unchanged, so downstream users should be unaffected. For any tasks that needs the location of the upstream source code there is [ros/rosdistro](https://github.com/ros/rosdistro) and [ros-infrastructure/rosinstall_generator](https://github.com/ros-infrastructure/rosinstall_generator).

**Pull request merged**
