### PR TITLE
Sensor parsing

### PR DESCRIPTION
**Pull request by rhaschke**
Allow for generic parsing of sensors.
This PR provides some convenience methods to parse sensor elements in URDF using plugin libs found by the pluginlib mechanism. This builds on top of  https://github.com/ros/urdfdom/pull/84 and https://github.com/ros/urdfdom_headers/pull/22. 
Example usage can be seen in the [unittest of tactile_toolbox](https://github.com/ubi-agni/tactile_toolbox/blob/master/urdf_tactile/test/unit_test.cpp#L45).

### CODE REVIEW

**Comment by rhaschke** [comment]
@jacquelinekay Do you think this set of PRs (https://github.com/ros/urdfdom_headers/pull/22, https://github.com/ros/urdfdom/pull/84, and this one) to allow basic, plugin-based parsing of `<sensor>` tags has a chance to be integrated into `kinetic`?

I know, you are thinking about [urdf2](http://discourse.ros.org/t/urdf-ng-parser-tools-wishlist/55), but I guess this will take a little bit longer ;-)

The code is ABI-compatible to the previous libs (building on urdfdom 0.4) and we used it successfully for some weeks now. Actually, the code primarily touches the sensor parsing only, which wasn't productive before at all.

**Comment by rhaschke** [comment]
Friendly ping. 
I know the checks are failing. This is due to changes required also in urdfdom and urdfdom_headers.
It would be really cool to get the modularized sensor parsing (using pluginlib) in at some point ;-)

**Comment by clalancette** [comment]
@rhaschke I know it has been a long time on this one, and for that I'm sorry.  Are you still interested in getting this in?  If so, can you please give us a better description of what exactly you are trying to achieve with this PR?  Also, I believe the build should be able to complete now.  Finally, I think we'd want to have some additional unit tests to cover this functionality, so to go forward with this we'd also want that.  Thank you for your patience.

**Comment by rhaschke** [comment]
@clalancette I'm still very interested to get the sensor description parsing more modularized. The idea is to extend sensor support beyond Camera and Ray, but to allow any custom sensor description with appropriate parsers provided via plugins. We use that mechanism for example to describe tactile sensors for our [tactile toolbox](https://github.com/ubi-agni/tactile_toolbox).  For a detailed motivation, please have a look at ros/urdfdom#84.
This PR is only the very last in a whole series of PRs also involving ros/urdfdom_headers#22 and ros/urdfdom#84. Hence, it cannot compile without those. And yes, there are unittests provided in urdfdom already.

**Comment by sloretz** [comment]
@rhaschke Thanks for the pull request! The urdf packages have been moved to their own repo as part of #195. Would you mind moving this to https://github.com/ros/urdf?

**Pull request closed without merging**
